# Generated by Django 5.0.6 on 2024-05-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('nom_propietaire', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('scanned_date', models.DateField(auto_now_add=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.archivecategory')),
                ('physical_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.physicaldocument')),
            ],
        ),
    ]
