# Generated by Django 5.0.6 on 2024-08-03 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepportInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('content_page', models.PositiveBigIntegerField(default=1)),
                ('date_venu', models.DateField(auto_now_add=True)),
                ('photo_document', models.ImageField(upload_to='photo_document/')),
                ('is_receive_secretary', models.BooleanField(default=False)),
                ('is_receive_twice_confirm', models.BooleanField(default=False)),
                ('is_receive_twice_rejetter', models.BooleanField(default=False)),
                ('is_archive', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
