# Generated by Django 5.0.6 on 2024-08-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='poste',
            field=models.CharField(choices=[('secretaire', 'Secretaire'), ('agent', 'Agent'), ('maire', 'Maire'), ('archiviste', 'Archiviste'), ('administrateur', 'Administrateur')], default='administrateur', max_length=100),
        ),
    ]
